### ISSUE TITLE
Manual Encryption Works with KMS, but Puppet Runs Fail with Credentials Error

### ISSUE THREAD

**Issue by bxbrenden** [adenot/hiera-eyaml-kms#10]
## Description
I can manually encrypt strings with eyaml using KMS as a backend, but when puppet runs, it fails with an error.

Here is an example of a working, manual encryption:
```
[root@redacted]$ eyaml encrypt -n kms -l "manually encrypted" -s "workplz"
[hiera-eyaml-core] Loaded config from /etc/puppetlabs/code/eyaml/config.yaml
manually encrypted: ENC[KMS,AQICAHhkrRxMYwTweduztMFVGJvPNtMGRqUe520ES6xNCH8eMQFNGhsQ40x5a+c/tuq8WtIBAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVMs3JBFy+ahr7NoeAgEQgCKx726lcmxigLcaOGpCFGxY2odhV0C02plQjEDErtEAbvff]

OR

manually encrypted: >
    ENC[KMS,AQICAHhkrRxMYwTweduztMFVGJvPNtMGRqUe520ES6xNCH8eMQFNGhsQ40x5
    a+c/tuq8WtIBAAAAZTBjBgkqhkiG9w0BBwagVjBUAgEAME8GCSqGSIb3DQEH
    ATAeBglghkgBZQMEAS4wEQQMVMs3JBFy+ahr7NoeAgEQgCKx726lcmxigLca
    OGpCFGxY2odhV0C02plQjEDErtEAbvff]
```
However, when I try to run Puppet against that same compile master, it throws an error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, unable to sign request without credentials set at </path/to/manifest> on node <node_name>
```

## Relevant Configuration
Here are the relevant contents of my hiera.yaml file:
```
# hiera.yaml Managed by Puppet
version: 5
defaults:
  datadir: ../code/hiera/%{::my_hiera_repo}
  data_hash: yaml_data
hierarchy:

  - name: "environment/hostgroup"
    path: "environments/%{my_env}/%{my_hostgroup}.eyaml"
    lookup_key: eyaml_lookup_key
    options:
     kms_aws_region: 'us-west-2'
     kms_key_id: 'alias/hiera-eyaml-key'
     kms_aws_profile: 'DevOps'
```
And here is the content of my $EYAML_CONFIG file `/etc/puppetlabs/code/hiera.yaml`:
```
---
kms_key_id: 'alias/hiera-eyaml-key'
kms_aws_region: 'us-west-2'
kms_aws_profile: 'DevOps'
```

This is the section of the IAM policy that enables  my `hiera-eyaml` IAM user to encrypt, decrypt, etc.:
```
{
    "Sid" : "Allow use of the key",
    "Effect" : "Allow",
    "Principal" : {
      "AWS" : [ "arn:aws:iam::<redacted>:role/DevOpsFullAccess", "arn:aws:iam::<redacted>:user/hiera-eyaml" ]
    },
    "Action" : [ "kms:Encrypt", "kms:Decrypt", "kms:ReEncrypt*", "kms:GenerateDataKey*", "kms:DescribeKey" ],
    "Resource" : "*"
  }
```

I have the AWS credentials set in `~/.aws/credentials` for the `hiera-eyaml` user and that key corresponds to a user that has permissions to encrypt and decrypt using the hiera-eyaml-kms key I created in AWS. 

I have tried adding the `$AWS_ACCESS_KEY_ID` and `$AWS_SECRET_KEY` environment variables to `/etc/profile.d` so that they are available to puppet, but this does not work either. I noticed that issue #2 was similar, but the solution was not clear. 

Please help, and let me know what else I can provide.
