### ISSUE TITLE
Error when trying to use KMS encryption method

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [adenot/hiera-eyaml-kms#7]
`Error: Evaluation Error: Error while evaluating a Function Call, missing region; use :region option or export region name to ENV['AWS_REGION']`

I have `kms_aws_region: 'us-west-2'` in /etc/eyaml/config.yaml and it works just fine.  I've also tried adding both "region" and "aws_region" to the default hiera.yaml under the options field.  The `eyaml` commandline tool works without error, only puppetserver fails.

I also updated the kms.rb file on disk with the most recent github files to no change.

**Comment by JohnPeacockMessageSystems** [comment]
Error message is wrong/misleading and the documentation is lacking.  The change to hiera.yaml is as follows (for Hiera 5):
``` yaml
     ....
     lookup_key: eyaml_lookup_key # eyaml backend
     options:
      kms_aws_region: us-west-2
```
